### PR TITLE
doxygen + teleport

### PR DESCRIPTION
**Pull request by nadamswsu**
2 commits added. Comments are now compatible with doxygen and /t teleports the user to a predetermined location.

### CODE REVIEW

**Comment by ryansteeters** [comment]
Looks good, Noah. I see that the method is called tokenizev2, I assume that is because there is already an existing tokenize that didn't work. Maybe try renaming tokenizev2 to just tokenize and remove the original method just to make it clear the use of the function

**Review by Dustin-Layne — COMMENTED** [review]
The code looks pretty good but I would also suggest cleaning up the code a little bit. Removing comments such as "second attempt" and "tokenizev2" to "tokenize".

**Comment by w050asg** [comment]
Looks good glad to see doxygen comments. There does seem to be a fair amount of commented code that looks like it might not be used anymore. It may help with clarity to remove some of those and maybe take a pass at function and variable names.

**Comment by mistcurve** [comment]
Good job adding the doxygen comments. I agree with dustin that some of the names of things could be cleaned up a bit.

**Pull request merged**
