### PR TITLE
Added game pause visuals

### PR DESCRIPTION
**Pull request by jrichards1999**
Used glfw drawing to add visual elements to the pause menu.  This pull request completes user story D tasks #4 and #6

### CODE REVIEW

**Review by Dustin-Layne — COMMENTED** [review]
A lot of code to look through but it all looks pretty standard to me. No alarms going off when looking at anything. I was slightly confused on what some of the methods do, but I understand the big picture of the pull request. Nice work.

**Review by nadamswsu — APPROVED** [review]
Nice work on a lot of code. There are a few places where I would add some comments but otherwise looks really good.

**Comment by w050asg** [comment]
Looks good the comments that you added for doxygen were really good. I might consider adding in a few regular comments to help explain what a few areas do but other than that it looks great

**Comment by ryansteeters** [comment]
I agree with Noah and Dustin, Jon. There is a lot to look at here, so I understand if it is a lot to go back through, but comments could make it less frightening

**Pull request merged**
